/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as authSignupImport } from "./routes/__auth/signup";
import { Route as authLoginImport } from "./routes/__auth/login";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute
} as any);

const authSignupRoute = authSignupImport.update({
  path: "/signup",
  getParentRoute: () => rootRoute
} as any);

const authLoginRoute = authLoginImport.update({
  path: "/login",
  getParentRoute: () => rootRoute
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/__auth/login": {
      id: "/__auth/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof authLoginImport;
      parentRoute: typeof rootRoute;
    };
    "/__auth/signup": {
      id: "/__auth/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof authSignupImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login": typeof authLoginRoute;
  "/signup": typeof authSignupRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof authLoginRoute;
  "/signup": typeof authSignupRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/__auth/login": typeof authLoginRoute;
  "/__auth/signup": typeof authSignupRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/login" | "/signup";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/login" | "/signup";
  id: "__root__" | "/" | "/__auth/login" | "/__auth/signup";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  authLoginRoute: typeof authLoginRoute;
  authSignupRoute: typeof authSignupRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/__auth/login",
        "/__auth/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/__auth/login": {
      "filePath": "__auth/login.tsx"
    },
    "/__auth/signup": {
      "filePath": "__auth/signup.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
