/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as usersSignupImport } from './routes/__users/signup'
import { Route as usersLoginImport } from './routes/__users/login'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const usersSignupRoute = usersSignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const usersLoginRoute = usersLoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/__users/login': {
      id: '/__users/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof usersLoginImport
      parentRoute: typeof rootRoute
    }
    '/__users/signup': {
      id: '/__users/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof usersSignupImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof usersLoginRoute
  '/signup': typeof usersSignupRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof usersLoginRoute
  '/signup': typeof usersSignupRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/__users/login': typeof usersLoginRoute
  '/__users/signup': typeof usersSignupRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup'
  id: '__root__' | '/' | '/__users/login' | '/__users/signup'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  usersLoginRoute: typeof usersLoginRoute
  usersSignupRoute: typeof usersSignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  usersLoginRoute: usersLoginRoute,
  usersSignupRoute: usersSignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/__users/login",
        "/__users/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/__users/login": {
      "filePath": "__users/login.tsx"
    },
    "/__users/signup": {
      "filePath": "__users/signup.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
