ALTER TABLE games
ALTER COLUMN id SET NOT NULL;

ALTER TABLE roles
ALTER COLUMN id SET NOT NULL;

ALTER TABLE seasons
ALTER COLUMN id SET NOT NULL;

ALTER TABLE teams
ALTER COLUMN id SET NOT NULL;

ALTER TABLE user_role
ALTER COLUMN id SET NOT NULL;