ALTER TABLE user_role
ALTER COLUMN user_id SET NOT NULL,
ALTER COLUMN role_id SET NOT NULL;

ALTER TABLE games
ALTER COLUMN game_time SET NOT NULL,
ALTER COLUMN location SET NOT NULL,
ALTER COLUMN home_team_id SET NOT NULL,
ALTER COLUMN away_team_id SET NOT NULL;

ALTER TABLE seasons
ALTER COLUMN start_date SET NOT NULL,
ALTER COLUMN end_date SET NOT NULL;